[tool.poetry]
name = "fsw-sp"
version = "0.1.0"
description = ""
authors = ["Crashkill <fabriciocardosolima@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
supabase-auth = "^2.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
